---
title: "Healthcare"
output: html_notebook
---

Initial Setup:

```{r}
library(dplyr)
library(ggplot2)
library(tidyverse)
library(readr)
library(maps)
library(maptools)
library(ggmap)
library(doBy)
library(mapproj)
library(ggthemes)
library(reshape2)
```


Data

```{r}
setwd("/cloud/project/Mini Project 2/Mini Project 2 Adriana_Elisa")
coverage <- read_csv("hcare_cov.csv")
spending <- read_csv("hcare_spend.csv")
```

```{r}
capFirst <- function(s) {
    paste(toupper(substring(s, 1, 1)), substring(s, 2), sep = "")
}
```

```{r}
gusa <- map_data("state")
gusa$region <- capFirst(gusa$region)
```





```{r}
y <- spending %>%
  select(Location, `2013__Total Health Spending`)%>%
  group_by(Location)%>%
  filter(Location != 'United States')%>%
  filter(`2013__Total Health Spending` > 60500)%>%
  #summarise(number_recipients=n()) %>%
  arrange(desc(`2013__Total Health Spending`))

y$Location <- factor(y$Location, levels =   y$Location[order(y$`2013__Total Health Spending`, decreasing = T)])
y
y %>%
ggplot() +
geom_bar(aes(x=Location, y= `2013__Total Health Spending` , fill= Location), stat = 'identity')+
theme(axis.text.x=element_text(angle=40, hjust=1, vjust=1))+ labs(x='Location')+ labs(y= 'Total spent in 2013')
```



```{r}
z <- spending %>%
  select(Location, `2014__Total Health Spending`)%>%
  group_by(Location)%>%
  filter(Location != 'United States')%>%
  filter(`2014__Total Health Spending` > 65000)%>%
  #summarise(number_recipients=n()) %>%
  arrange(desc(`2014__Total Health Spending`))

z$Location <- factor(z$Location, levels =   z$Location[order(z$`2014__Total Health Spending`, decreasing = T)])
z
z %>%
ggplot(color = 'purple') +
geom_bar(aes(x=Location, y=`2014__Total Health Spending`, fill= Location), stat = 'identity')+
theme(axis.text.x=element_text(angle=40, hjust=1, vjust=1))+ labs(x='Location')+ labs(y= 'Total spent in 2014')
```



```{r}
joined <- left_join(y,z,'Location')
joined

my_data_long <- melt(joined, id.vars = c("Location"))
ggplot(data=my_data_long,aes(x=Location, y=value, fill=variable, color=variable, alpha=variable)) +
  geom_bar(stat="identity",position ="identity") +
  scale_colour_manual(values=c("lightblue4","red")) +
  scale_fill_manual(values=c("blue","white")) +
  scale_alpha_manual(values=c(0.2, 0)) +
theme(axis.text.x=element_text(angle=40, hjust=1, vjust=1))+ labs(x='Location')+ labs(y= 'Total spent')
```





```{r}
data<- spending%>%
  filter( Location != "United States")%>%
  mutate(Location = fct_recode(Location, "South dakota"= "South Dakota", "South carolina"= "South Carolina", "Rhode island"= "Rhode Island", "District of columbia"= "District of Columbia", "New hampshire"= "New Hampshire", "New mexico"= "New Mexico", "New jersey"= "New Jersey", "New york"= "New York", "North carolina"= "North Carolina", "West virginia"= "West Virginia", "North dakota"= "North Dakota"))%>%
  select(region= Location, `2014__Total Health Spending`)%>%
  mutate(rspending = rank(`2014__Total Health Spending`))%>%
  mutate(pcls = cut(`2014__Total Health Spending`, quantile(`2014__Total Health Spending`, seq(0, 1, len = 6)), include.lowest = TRUE))
```


```{r}
spd_total <- left_join(gusa, data, "region")
head(spd_total)
```


```{r}

txtVal <- summaryBy(long + lat + rspending ~ region, data=spd_total, FUN=mean, keep.names=T)

ggplot(spd_total) +
    geom_polygon(aes(long, lat, group = group, fill = rspending),
                 color = "grey") +
    coord_map("bonne", parameters=45) + geom_text(aes(x=long, y=lat, label=rspending), data=txtVal, col="red", cex=2.5) + ggtitle("Map of Spending Total Rank in 2014")
```






Creating the map

```{r}
cleancov<- coverage %>%
  #filter( `2014__Other Public` != "N/A")%>%
  filter( Location != "United States")%>%
  mutate(Location = fct_recode(Location, "South dakota"= "South Dakota", "South carolina"= "South Carolina", "Rhode island"= "Rhode Island", "District of columbia"= "District of Columbia", "New hampshire"= "New Hampshire", "New mexico"= "New Mexico", "New jersey"= "New Jersey", "New york"= "New York", "North carolina"= "North Carolina", "West virginia"= "West Virginia", "North dakota"= "North Dakota"))%>%
  select(region= Location, `2014__Total`)%>%
  mutate(rcov = rank(`2014__Total`))%>%
  mutate(Percentiles = cut(`2014__Total`, quantile(`2014__Total`, seq(0, 1, len = 6)), include.lowest = TRUE))
head(cleancov)
  
```


```{r}
cov_total <- left_join(gusa, cleancov, "region")
head(cov_total)
```






```{r}
txtVal1 <- summaryBy(long + lat + rcov ~ region, data=cov_total, FUN=mean, keep.names=T)

ggplot(cov_total) +
    geom_polygon(aes(long, lat, group = group, fill = rcov),
                 color = "grey") +
    coord_map("bonne", parameters=45) + geom_text(aes(x=long, y=lat, label=rcov), data=txtVal1, col="red", cex=2.5)+ ggtitle("Map of Coverage Total Rank in 2014")
```

```{r}

ggplot(cov_total) +
    geom_polygon(aes(long, lat, group = group, fill = Percentiles),
                 color = "grey") +
    coord_map("bonne", parameters=45) +
    ggthemes::theme_map() +
    scale_fill_brewer(palette = "Greens") + ggtitle("Map of Percentiles of Coverage Total in 2014")
```





```{r}
ggplot(spd_total) +
    geom_polygon(aes(long, lat, group = group, fill = pcls),
                 color = "grey") +
    coord_map("bonne", parameters=45) +
    ggthemes::theme_map() +
    scale_fill_brewer(palette = "Purples") + ggtitle("Map of Percentiles of Spending Total in 2014")
```









    
