---
title: "Mini Project 2 : Data wrangling and visualization"
output:
  html_document:
    toc: yes
    toc_depth: 2
    toc_float: true
---


## Administrative Notes

* **Peer graded Presentations**: Day 3, PM Sessions
* **Learning Goal**: To make informative, appropriate, and compelling data graphics after reshaping the data
<!--
* **Technical Skills**: `ggplot2` package
-->

## The Details

You will work with a partner or two to write a short blog post that contains atleast one data graphic. Your goal is to tell us something interesting using a well-crafted, thoughtfully-prepared data graphic. One data graphic should suffice, but you may include more if you choose.

Your blog post should be short. We envision an introductory paragraph that explains your findings and provides some context to your data, the data graphic, and then a caption-like paragraph providing more detail about what to look for in the data graphic and how to interpret it. That is it. You will not earn more points by including more words or data graphics. What we are looking for is something that is insightful and well-crafted. As always, you should spend some time thinking about context, scale, color, etc.

Here are some examples of articles that are similar in spirit to yours. Most of these are much longer than yours will be, and may contain multiple graphics, but the idea is similar: use a good data graphic to tell us something we don't already know.

* [How to Tell Someone's Age When All You Know Is Her Name](https://fivethirtyeight.com/features/how-to-tell-someones-age-when-all-you-know-is-her-name/){target="_blank"}
* [A Better Way To Find The Best Flights And Avoid The Worst Airports](https://fivethirtyeight.com/features/fastest-airlines-fastest-airports/){target="_blank"}
* [NYC Taxis and Uber](http://toddwschneider.com/posts/analyzing-1-1-billion-nyc-taxi-and-uber-trips-with-a-vengeance/){target="_blank"}
* [Data on people who went to ER for wall-punching](https://flowingdata.com/2016/01/14/data-on-people-who-wall-punching/){target="_blank"}


<!--
Create a visual to ANSWER ONE QUESTION: WHO DONATES? (Related subquestions you may also answer: How are donations distributed across countries? Who donates to whom? Are there any patterns, for example some group of countries tends to donate only to some specific group of other countries?)
Create visuals from provided data to effectively answer specific questions.
-->

## The Data 

We will be using the data from the [Henry J Kaiser Family Foundation (KFF)](https://www.kff.org/)

1. [Health Insurance Coverage of the Total Population - Includes years 2013-2016](https://www.kff.org/other/state-indicator/total-population/)
2. [Health Care Expenditures by State of Residence (in millions)  Includes years 1991-2014](https://www.kff.org/other/state-indicator/health-care-expenditures-by-state-of-residence-in-millions/)

Data is already in  1_Data folder. 

## The Questions 

1. Is there a relationship between healthcare coverage and healthcare spending in the United States?
2. How does the spending distribution change across geographic regions in the United States?
3. Does the relationship between healthcare coverage and healthcare spending in the United States change from 2013 to 2014?


Build your solution with any tool you like. This could be a single graph, multiple graphs organized in your preferred layout or even an interactive dashboard if you prefer. Remember that your primary goal is effectiveness. 


## What to do 

1. As a group:
    + Describe your data briefly in a textual manner.
    + Do not forget to mention how you dealt with missing data (if any).
    + Try to think of one or two research questions from the data. For the healthcare data, you may combine the coverage and spending for relevant years and formulate some questions you think would be worth exploring.
    + Clean or reshape the data by all the necessary transformations to get a final dataset that you will use to generate the diagrams. Think of graphs or charts that will throw some light in the direction of the research questions you posed.
    + If you are using data that is included in a separate file (like an Excel or `.csv` file), submit this too. If you do not, we will not be able to *reproduce and replicate* your results.
    + Try to sum up your findings in a short paragraph in the end.
2. Make sure to [avoid the normal Data Viz mistakes]((http://dicook.org/2018/04/14/content/post/2018-04-14-rookie-mistakes/))
4. You can review Rmarkdown syntax here:
- [SWC: Rmarkdown overview](http://swcarpentry.github.io/r-novice-gapminder/15-knitr-markdown/index.html)
    


## Presentation

1. You will share with me your Project via RStudio cloud and you will present it during the camp
2. Others are to provide feedback on projects.
