---
title: "Dara"
output: html_document
---


```{r}
library(tidyverse)
library(broom)
library(ggplot2)
library(readxl)
```


```{r}
teen_birth <- read_csv("../Data/teen_birth.csv")
Education <- read_csv("../Data/Education.csv")
Unemployment <- read_excel("../Data/Unemployment.xls", skip = 7)
```


```{r}
Education


unique(teen_birth$Year)

Unemployment



```
```{r}
names(Unemployment)
names(Education)
```
```{r}

Education=Education%>%select(1,44,45,46,47)
teen_birth=teen_birth%>%filter(Year=="2015")%>%select("Combined FIPS Code", "Birth Rate", "Year")
unemployment2015 <- Unemployment %>%
  rename(FIPS = FIPStxt) %>%
  select(FIPS, State, Area_name, 39:42) %>%
  rename(LaborForce = Civilian_labor_force_2015, Employed = Employed_2015, Unemployed = Unemployed_2015, UnemploymentRate = Unemployment_rate_2015)
```
```{r}
teen_birth=teen_birth%>%mutate(`Combined FIPS Code`=as.character(`Combined FIPS Code`))
data=teen_birth%>%inner_join(Education,by=c("Combined FIPS Code"="FIPS Code"))
data=data%>%inner_join(unemployment2015, by=c("Combined FIPS Code"="FIPS"))

data=data%>%rename(Less_than_high_school=`Percent of adults with less than a high school diploma, 2013-17`,high_school=`Percent of adults with a high school diploma only, 2013-17`,some_college=`Percent of adults completing some college or associate's degree, 2013-17`,college=`Percent of adults with a bachelor's degree or higher, 2013-17`)
data
```


```{r}
data%>%ggplot()+geom_point(aes(y=`Birth Rate`, x=`Less_than_high_school`))

data%>%ggplot()+geom_point(aes(y=`Birth Rate`, x=`high_school`))


data%>%ggplot()+geom_point(aes(y=`Birth Rate`, x=`some_college`))


data%>%ggplot()+geom_point(aes(y=`Birth Rate`, x=`college`))


data%>%ggplot()+geom_point(aes(y=`Birth Rate`, x=`UnemploymentRate`))
```

```{r}
model=lm(`Birth Rate`~UnemploymentRate+Less_than_high_school+high_school+college,data=data)

summary(model)
plot(model)
```


```{r}

model=lm(log(`Birth Rate`)~UnemploymentRate+Less_than_high_school+high_school+college,data=data)

summary(model)
plot(model)
```



```{r}

model=lm(`Birth Rate`~UnemploymentRate+Less_than_high_school+high_school+college+I(UnemploymentRate^2)+I(Less_than_high_school^2)+I(high_school^2)+I(college^2),data=data)

summary(model)
plot(model)
```


```{r}

model=lm(`Birth Rate`~UnemploymentRate+Less_than_high_school+high_school+college+I(UnemploymentRate^(1/2))+I(Less_than_high_school^(1/2))+I(high_school^(1/2))+I(college^(1/2)),data=data)

summary(model)
plot(model)
```



```{r}

model=lm(`Birth Rate`~UnemploymentRate+Less_than_high_school+high_school+college+I(log(UnemploymentRate))+I(log(Less_than_high_school))+I(log(high_school))+I(log(college)),data=data)

summary(model)
plot(model)
```


```{r}
model=lm(`Birth Rate`^(1/2)~UnemploymentRate+Less_than_high_school+high_school+college,data=data)

summary(model)
plot(model)
```


```{r}
library(maptools)
library(tmap) 
library(sf)
library(maps)


library(maps)
library(dplyr)

data(county.fips)



## merge population data with county.fips to make sure color column is
## ordered correctly.
data=data%>%mutate(`Combined FIPS Code`=as.integer(`Combined FIPS Code`))


```


```{r}
# Load the county data from the maps package
cnty <- st_as_sf(map("county", plot = FALSE, fill = TRUE))



cnty2 <- cnty %>%
         left_join(county.fips, by=c("ID" = "polyname"))

cnty.data <- inner_join(cnty2, data , by=c("fips"="Combined FIPS Code") )

tm_shape(cnty.data) + tm_fill(col = "Birth Rate", palette = "Greens") +tm_legend(outside = TRUE)
```